invoice_gen/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include(('users.urls', 'users'), namespace='users'))
]

users/urls.py
"""Users URLs"""

# Django
from django.urls import path
from django.shortcuts import render
from django.http import request

# Models
from users import views

urlpatterns = [
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),

    path(
        route='logout/',
        view=views.auth_views.LogoutView.as_view(),
        name='logout'
    ),

    path(
        route='dashboard/',
        view=views.dashboardView,
        name='dashboard'
    ),
]

users/models.py
"""Users models"""

# Django
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    """Profile model.
    Proxy that extends user information."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    abn = models.CharField(
        max_length=20,
        blank=True,
        null=True
    )
    phone = models.CharField(
        max_length=30,
        blank=True,
        null=True
    )

    address = models.CharField(max_length=50)

    bank_name = models.CharField(max_length=30)
    account_name = models.CharField(max_length=30)
    account_bsb = models.CharField(max_length=10)
    account_number = models.CharField(max_length=20)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/forms.py
"""Users forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from django.forms.fields import EmailField
from users.models import Profile

style_attributes = {'class': 'form-control'}


class ProfileForm(forms.Form):
    """Signup form for user information."""

    username = forms.CharField(
        min_length=5,
        max_length=50,
        widget=forms.widgets.TextInput(attrs=style_attributes),
    )

    password = forms.CharField(
        max_length=100,
        widget=forms.widgets.PasswordInput(attrs=style_attributes),
    )
    password_confirm = forms.CharField(
        max_length=100,
        widget=forms.widgets.PasswordInput(attrs=style_attributes),
    )

    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.widgets.TextInput(attrs=style_attributes),
    )

    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        widget=forms.widgets.TextInput(attrs=style_attributes),
    )

    email = forms.CharField(
        min_length=6,
        max_length=80,
        widget=forms.widgets.EmailInput(attrs=style_attributes),
    )

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data.get("username")
        username_used = User.objects.filter(username = username).exists()

        if username_used:
            raise forms.ValidationError(message="Username is already in use.")

        return username

    def clean(self):
        """Password Confirmation must match"""
        cleaned_data = super().clean()

        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError(message="Password confirmation does not match")

        return cleaned_data

    def save(self):
        print(self.cleaned_data)
        data = self.cleaned_data
        data.pop("password_confirm")
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views"""

# Django
from django.contrib.auth import views as auth_views
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls.base import reverse_lazy

# Forms
from users import forms


class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('users:dashboard')


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = forms.ProfileForm
    success_url = reverse_lazy('users:dashboard')

    def form_valid(self, form):
        """Process after Form validation"""
        form.save()
        return super().form_valid(form)


@login_required
def dashboardView(request):
    return render(request, 'users/dashboard.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block head_content %}
        {% endblock head_content %}


        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />

    </head>
    <body>

        {% include "nav.html" %}

        <div class="container mt-5">
            {% block content %}
            {% endblock content %}
        </div>

    </body>
</html>

templates/nav.html
<nav class="navbar navbar-light bg-light px-3">
    <span class="navbar-brand mb-0 h1">Invoice-Gen</span>
    <div>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">
                    Logout
                </a>
            </li>
        </ul>
    </div>
</nav>

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block head_content %}
        {% endblock head_content %}


        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />

    </head>
    <body>

        <div class="container mt-5">
            {% block content %}
            {% endblock content %}
        </div>

    </body>
</html>

templates/users/dashboard.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Landing</title>
{% endblock head_content %}

{% block content %}

  <h1>{{ request.user.username }}</h1>

{% endblock content %}

templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
    <title>Login</title>
{% endblock head_content %}

{% block content %}
<form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text"
        class="form-control" name="username" id="username" placeholder="">
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" class="form-control" name="password" id="password" placeholder="">
    </div>

    <button type="submit" class="btn btn-primary btn-block">Login</button>
</form>
<p class="mt-4">Do not have an account yet? <a href="{% url 'users:signup' %}">Sign up here.</a></p>
{% endblock content %}

templates/users/signup.html
{% extends 'users/base.html' %}

{% block head_content %}
    <title>User Signup</title>
{% endblock head_content %}

{% block content %}

    <form action="{% url 'users:signup' %}" method='Post'>
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" name="signup" id="signup" class="btn btn-primary btn-lg btn-block">SignUp</button>
    </form>

    <p class="mt-4">Already have an account? <a href="{% url 'users:login' %}">Log in here.</a></p>
{% endblock content %}